language: python
python:
    - "3.5"
install: pip install -r requirements.txt
addons:
  postgresql: "9.4"
script:
    - coverage run --source=api manage.py test -v=2
    - coverage report
branches:
  only:
      - master
      - develop
